- hosts: localhost
  pre_tasks:
  - name: Update Apt Packages
    become: true
    ansible.bultin.apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - full
      - core

  tasks:
  - include: tasks/core.yaml
    #    - include: tasks/rust.yaml
    #    - include: tasks/go.yaml
    #    - include: tasks/haskell.yaml
    #    - include: tasks/docker.yaml
    #    - include: tasks/ssh.yaml
    #    - include: tasks/git.yaml
    #    - include: tasks/dotfiles.yaml
    #    - include: tasks/nvim.yaml
    #    - include: tasks/apps.yaml
    #    - include: tasks/alacritty.yaml
    #    - include: tasks/zsh.yaml
    #
