- name: Install tmux
  become: True
  ansible.builtin.apt:
    name:
      - tmux
  tags:
    - full
    - apps

- name: Add OBS Studio PPA repository
  become: True
  ansible.builtin.apt_repository:
    repo: ppa:obsproject/obs-studio
  tags:
    - full
    - obs
    - apps


- name: Install OBS Studio
  become: True
  ansible.builtin.apt:
    name:
      - obs-studio
  tags:
    - full
    - obs
    - apps

- name: Add Kdenlive repository
  become: True
  ansible.builtin.apt_repository:
    repo: ppa:kdenlive/kdenlive-stable
  tags:
    - full
    - kdenlive
    - apps

- name: Install Kdenlive
  become: True
  ansible.builtin.apt:
    name:
      - kdenlive
  tags:
    - full
    - kdenlive
    - apps

- name: Check if jetbrains-toolbox is already installed
  shell: command -v jetbrains-toolbox
  register: jt_exists
  ignore_errors: yes
  tags:
    - full
    - jetbrains
    - apps

- name: Download Jetbrains toolbox archive
  when: jt_exists is failed
  get_url:
    url: "https://download-cdn.jetbrains.com/toolbox/jetbrains-toolbox-1.27.1.13673.tar.gz"
    dest: "/tmp/jetbrains-toolbox.tar.gz"
    mode: '0755'
    checksum: sha256:5108db9f3ee2828e50887a1f4fb41ce50a4df8c1ebbef87cd931bbb726661d5e
  tags:
    - full
    - jetbrains
    - apps

- name: Unarchive Jetbrains Toolbox archive
  when: jt_exists is failed
  become: true
  ansible.builtin.unarchive:
    src: "/tmp/jetbrains-toolbox.tar.gz"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin"
    remote_src: yes
  tags:
    - full
    - jetbrains
    - apps

- name: Check if bazel is already installed
  shell: command -v bazel
  register: bazel_exists
  ignore_errors: yes
  tags: 
    - full
    - bazel
    - apps

- name: Install bazel
  when: bazel_exists is failed
  become: true
  get_url:
    url: "https://github.com/bazelbuild/bazelisk/releases/download/v1.15.0/bazelisk-linux-amd64"
    dest: "/usr/local/bin/bazel"
    mode: '0555'
  tags: 
    - full
    - bazel
    - apps

