- name: Install system packages
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - cmake
      - libpthread-stubs0-dev
      - python3
      - git
      - make
      - curl
      - libffi-dev               ## Haskell Deps begin
      - libffi8ubuntu1
      - libgmp-dev
      - libgmp10
      - libncurses-dev
      - libncurses5
      - libtinfo5               ## Haskell Deps end
      - libx11-dev              # XMonad Deps begin
      - libxft-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxss-dev              # XMonad Deps end
  tags:
    - full
    - core
