- name: Install system packages
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - cmake
      - libpthread-stubs0-dev
      - python3
      - git
      - make
      - curl
  tags:
    - full
    - core
