- name: Check if go is already installed
  shell: command -v jetbrains-toolbox
  register: jt_exists
  ignore_errors: yes
  tags:
    - full
    - jetbrains

- name: Download Jetbrains toolbox archive
  when: jt_exists is failed
  get_url:
    url: "https://download-cdn.jetbrains.com/toolbox/jetbrains-toolbox-1.27.1.13673.tar.gz"
    dest: "/tmp/jetbrains-toolbox.tar.gz"
    mode: '0755'
    checksum: sha256:5108db9f3ee2828e50887a1f4fb41ce50a4df8c1ebbef87cd931bbb726661d5e
  tags:
    - full
    - jetbrains

- name: Unarchive Jetbrains Toolbox archive
  when: jt_exists is failed
  become: true
  ansible.builtin.unarchive:
    src: "/tmp/jetbrains-toolbox.tar.gz"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin"
    remote_src: yes
  tags:
    - full
    - jetbrains
