- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh"
    state: directory
    mode: 0700
  tags:
    - full
    - ssh

- name: Copy Github's private key
  vars:
    file_name: ".ssh/id_ed25519_gh"
  ansible.builtin.copy:
    src: "./{{ file_name }}"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/{{ file_name }}"
    mode: 0600
  tags:
    - full
    - ssh

- name: Copy Github's public key
  vars:
    file_name: ".ssh/id_ed25519_gh.pub"
  ansible.builtin.copy:
    src: "./{{ file_name }}"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/{{ file_name }}"
    mode: 0600
  tags:
    - full
    - ssh

- name: Add github.com as known host for ssh
  ansible.builtin.known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}'"
    state: present
  tags:
    - full
    - ssh

