- name: Install xmonad
  shell: |
    cd "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/xmonad/xmonad"
    stack install
  tags:
    - full
    - xmonad

- name: Import xmonad as window manager
  shell: |
    cp xmonad.xsession "{{ lookup('ansible.builtin.env', 'HOME') }}/.xsession"
    cp xmonad.desktop /usr/share/xsessions/xmonad.desktop
  tags:
    - full
    - xmonad
